#!/usr/bin/python3

"""
### RUN motor config
python3 -m moteus.moteus_tool --target 1 --calibrate

### RUN moteus gui
python3 -m moteus_gui.tview --devices=1

#############   commands
conf set id.id 2 # change number for id 1,2,3,4
conf write
### NOW --- reconnect tview with new id
conf set servopos.position_min nan
conf set servopos.position_max nan
conf set servo.max_velocity 125.000000
conf set servo.max_position_slip 0.2
conf set servo.flux_brake_min_voltage 26.0
conf set servo.default_timeout_s 0.7
conf set servo.pwm_rate_hz 15000
conf set servo.derate_temperature 60
conf write


### move for test
d pos nan 7 2 
d pos nan 10 1 
d stop

"""

import time
import rospy
import asyncio
import math
import moteus
import threading
import sys
import signal
from std_msgs.msg import Float32, Bool
from vitulus_msgs.msg import Moteus_controller_state, Power_status
import traceback


class RobotSpec:
    FRONT_LEFT_ID = 1
    FRONT_RIGHT_ID = 2
    REAR_LEFT_ID = 3
    REAR_RIGHT_ID = 4
    REDUCER = 13
    WHEEL_DIA = 0.21  # meters
    ROTATION_DISTANCE = (WHEEL_DIA * math.pi) / REDUCER
    METER_ROTATION = 1 / ROTATION_DISTANCE
    MOT_RPS_TO_WHEEL_RAD = (2 * math.pi) / REDUCER
    WHEEL_RAD_TO_MOT_RPS = REDUCER / (2 * math.pi)
    TORQUE = 1.538461538  # Nm on motor
    torque_recent = TORQUE


class ControllerState:
    # Mode Constants
    MODE_STOPPED = 0
    MODE_FAULT = 1
    MODE_PWM = 5
    MODE_VOLTAGE = 6
    MODE_VOLTAGE_FOC = 7
    MODE_VOLTAGE_DQ = 8
    MODE_CURRENT = 9
    MODE_POSITION = 10  # Assumed to be the normal operational mode
    MODE_TIMEOUT = 11
    MODE_ZERO_VELOCITY = 12
    MODE_STAY_WITHIN = 13

    # Fault Constants
    FAULT_OK = 0
    FAULT_CALIBRATION = 32
    FAULT_MOTOR_DRV = 33
    FAULT_OVER_VOLTAGE = 34
    FAULT_ENCODER = 35
    FAULT_MOTOR_NOT_CONFG = 36
    FAULT_PWM_CYCLE_OVERRUN = 37
    FAULT_OVER_TEMP = 38
    FAULT_OUTSIDE_LIMIT = 39

    def __init__(self, id):
        self.id = id
        self.stamp = time.time()
        self.mode = ControllerState.MODE_STOPPED
        self.position = 0
        self.velocity = 0
        self.torque = 0
        self.voltage = 0
        self.temperature = 0
        self.fault = ControllerState.FAULT_OK
        self.position_offset_dist = 0
        self.position_offset_ang = 0
        self.position_ang = 0
        self.position_distance = 0
        self.velocity_ang = 0
        self.velocity_distance = 0

    def set_values(self, state):
        self.stamp = time.time()
        self.mode = state.values[moteus.Register.MODE]
        self.position = (state.values[moteus.Register.POSITION] * RobotSpec.ROTATION_DISTANCE) - self.position_offset_dist
        self.velocity = state.values[moteus.Register.VELOCITY]
        self.torque = state.values[moteus.Register.TORQUE]
        self.voltage = state.values[moteus.Register.VOLTAGE]
        self.temperature = state.values[moteus.Register.TEMPERATURE]
        self.fault = state.values[moteus.Register.FAULT]
        self.position_ang = (state.values[moteus.Register.POSITION] * RobotSpec.MOT_RPS_TO_WHEEL_RAD) - self.position_offset_ang
        self.position_distance = (state.values[moteus.Register.POSITION] * RobotSpec.ROTATION_DISTANCE) - self.position_offset_dist
        self.velocity_ang = (state.values[moteus.Register.VELOCITY] * RobotSpec.MOT_RPS_TO_WHEEL_RAD) - self.position_offset_ang
        self.velocity_distance = (state.values[moteus.Register.VELOCITY] * RobotSpec.ROTATION_DISTANCE) - self.position_offset_dist

    def set_offset(self, state):
        self.position_offset_dist = (state.values[moteus.Register.POSITION] * RobotSpec.ROTATION_DISTANCE)
        self.position_offset_ang = (state.values[moteus.Register.POSITION] * RobotSpec.MOT_RPS_TO_WHEEL_RAD)

    def get_status_msg(self, side=1):  # side -1 left, 1 right
        msg = Moteus_controller_state()
        msg.id = self.id
        msg.mode = self.get_mode(self.mode)
        msg.position = self.position * side
        msg.velocity = self.velocity * RobotSpec.ROTATION_DISTANCE * side
        msg.torque = self.torque * RobotSpec.REDUCER * side
        msg.voltage = self.voltage
        msg.temperature = self.temperature
        msg.fault = self.get_fault(self.fault)
        return msg

    def get_mode(self, code):
        if code == ControllerState.MODE_STOPPED:
            return "STOPPED"
        elif code == ControllerState.MODE_FAULT:
            return "FAULT"
        elif code == ControllerState.MODE_PWM:
            return "PWM"
        elif code == ControllerState.MODE_VOLTAGE:
            return "VOLTAGE"
        elif code == ControllerState.MODE_VOLTAGE_FOC:
            return "VOLTAGE_FOC"
        elif code == ControllerState.MODE_VOLTAGE_DQ:
            return "VOLTAGE_DQ"
        elif code == ControllerState.MODE_CURRENT:
            return "CURRENT"
        elif code == ControllerState.MODE_POSITION:
            return "POSITION"
        elif code == ControllerState.MODE_TIMEOUT:
            return "TIMEOUT"
        elif code == ControllerState.MODE_ZERO_VELOCITY:
            return "ZERO_VELOCITY"
        elif code == ControllerState.MODE_STAY_WITHIN:
            return "STAY_WITHIN"
        else:
            return str(code)

    def get_fault(self, code):
        if code == ControllerState.FAULT_OK:
            return "OK"
        elif code == ControllerState.FAULT_CALIBRATION:
            return "CALIBRATION_FAULT"
        elif code == ControllerState.FAULT_MOTOR_DRV:
            return "MOTOR_DRV_FAULT"
        elif code == ControllerState.FAULT_OVER_VOLTAGE:
            return "OVER_VOLTAGE"
        elif code == ControllerState.FAULT_ENCODER:
            return "ENCODER_FAULT"
        elif code == ControllerState.FAULT_MOTOR_NOT_CONFG:
            return "MOTOR_NOT_CONFG"
        elif code == ControllerState.FAULT_PWM_CYCLE_OVERRUN:
            return "PWM_CYCLE_OVERRUN"
        elif code == ControllerState.FAULT_OVER_TEMP:
            return "OVER_TEMP"
        elif code == ControllerState.FAULT_OUTSIDE_LIMIT:
            return "OUTSIDE_LIMIT"
        else:
            return str(code)


class MotorController:
    def __init__(self, id_nr):
        self.id = id_nr
        self.c = moteus.Controller(self.id)
        self.state = ControllerState(self.id)
        self.velocity = 0


class BaseController:
    def __init__(self):
        self.c_front_left = MotorController(RobotSpec.FRONT_LEFT_ID)
        self.c_front_right = MotorController(RobotSpec.FRONT_RIGHT_ID)
        self.c_rear_left = MotorController(RobotSpec.REAR_LEFT_ID)
        self.c_rear_right = MotorController(RobotSpec.REAR_RIGHT_ID)

        # Configuration for each motor
        self.motor_configs = [
            {'obj': self.c_front_left,  'name': "FRONT_LEFT",  'vel_cmd_multiplier': -1, 'ros_name_prefix': 'front_left'},
            {'obj': self.c_front_right, 'name': "FRONT_RIGHT", 'vel_cmd_multiplier':  1, 'ros_name_prefix': 'front_right'},
            {'obj': self.c_rear_left,   'name': "REAR_LEFT",   'vel_cmd_multiplier': -1, 'ros_name_prefix': 'rear_left'},
            {'obj': self.c_rear_right,  'name': "REAR_RIGHT",  'vel_cmd_multiplier':  1, 'ros_name_prefix': 'rear_right'},
        ]

        # Motor command parameters (previously magic numbers)
        self.MOTOR_FF_TORQUE = -0.1  # Consider if this needs to be directional
        self.MOTOR_KP_SCALE = 2.0
        self.MOTOR_KD_SCALE = 1.0
        self.MOTOR_WATCHDOG_TIMEOUT = 0.5
        self.DEFAULT_MAX_TORQUE = RobotSpec.TORQUE # Default max torque from RobotSpec

        # This will be updated by the ROS thread in the background.
        self.lock = threading.Lock()
        self.current_request = None
        self.motors_switch = False
        self.motors_power_switch = None
        self.motors_switch_pub = None
        self.stop_controller = False
        self.stop_power = False
        self.start_controller = False
        self.start_power = False
        self.ros_ready = False
        self.controller_status = False
        self.pub_front_left_velocity = rospy.Publisher("/base/front_left_wheel_real_vel", Float32, queue_size=10)
        self.pub_front_right_velocity = rospy.Publisher("/base/front_right_wheel_real_vel", Float32, queue_size=10)
        self.pub_rear_left_velocity = rospy.Publisher("/base/rear_left_wheel_real_vel", Float32, queue_size=10)
        self.pub_rear_right_velocity = rospy.Publisher("/base/rear_right_wheel_real_vel", Float32, queue_size=10)
        self.pub_front_left_angle = rospy.Publisher("/base/front_left_wheel_angle", Float32, queue_size=10)
        self.pub_front_right_angle = rospy.Publisher("/base/front_right_wheel_angle", Float32, queue_size=10)
        self.pub_rear_left_angle = rospy.Publisher("/base/rear_left_wheel_angle", Float32, queue_size=10)
        self.pub_rear_right_angle = rospy.Publisher("/base/rear_right_wheel_angle", Float32, queue_size=10)
        self.pub_front_left_state = rospy.Publisher("/base/front_left_wheel_state", Moteus_controller_state, queue_size=10)
        self.pub_front_right_state = rospy.Publisher("/base/front_right_wheel_state", Moteus_controller_state, queue_size=10)
        self.pub_rear_left_state = rospy.Publisher("/base/rear_left_wheel_state", Moteus_controller_state, queue_size=10)
        self.pub_rear_right_state = rospy.Publisher("/base/rear_right_wheel_state", Moteus_controller_state, queue_size=10)
        self.timer_slow = None

    async def run(self):
        ## Run Moteus controller

        # Wait for the power module open the motor switch
        wait_int_counter = 0
        wait_int_nr = 10
        while not self.ros_ready:
            time.sleep(0.3)
            if (wait_int_nr == wait_int_counter):
                rospy.logwarn("Still waiting for Power module enable motor power output...")
                # send turn on message to power module again
                new_msg = Bool()
                new_msg.data = True
                self.motors_switch_pub.publish(new_msg)
                wait_int_counter = 0
            wait_int_counter +=1

        for config in self.motor_configs:
            if config['obj'].c:
                await config['obj'].c.set_stop()

        start_time = time.time()
        while True:

            if self.stop_controller:
                if self.controller_status:
                    rospy.logwarn("Controller shutting down...")
                    for config in self.motor_configs:
                        motor_obj = config['obj']
                        if motor_obj.c:
                            try:
                                await motor_obj.c.set_stop()
                            except Exception as e:
                                rospy.logerr(f"Error stopping motor {motor_obj.id} ({config['name']}): {e}")
                            motor_obj.c = None
                        # Reset state more consistently
                        with self.lock:
                            motor_obj.state.mode = ControllerState.MODE_STOPPED
                            motor_obj.state.position = 0.0
                            motor_obj.state.velocity = 0.0
                            motor_obj.state.torque = 0.0
                            motor_obj.state.voltage = 0.0
                            motor_obj.state.temperature = 0.0
                            motor_obj.state.fault = ControllerState.FAULT_OK
                    
                    with self.lock:
                        self.stop_controller = False
                    with self.lock:
                        self.stop_power = True
                    with self.lock:
                        self.controller_status = False
                    rospy.logwarn("Controller is shut down.")

            if self.start_controller:
                rospy.loginfo("Controller starting...")
                for config in self.motor_configs:
                    motor_obj = config['obj']
                    # Re-initialize controller object if it's None or not the right type
                    if not isinstance(motor_obj.c, moteus.Controller):
                         motor_obj.c = moteus.Controller(motor_obj.id)
                    
                    if motor_obj.c: # Ensure it was created
                        await motor_obj.c.set_stop()
                        # Set initial position to current encoder reading, or zero.
                        # Using make_set_output_nearest ensures it starts from current position.
                        motor_obj.c.make_set_output_nearest(position=0.0) # Or math.nan if you want it to hold current

                with self.lock:
                    self.start_controller = False
                    self.controller_status = True
                rospy.loginfo("Controller started.")

            ### Set controllers velocities and read states #######
            with self.lock: # Lock for accessing shared RobotSpec.torque_recent
                current_max_torque = RobotSpec.torque_recent if RobotSpec.torque_recent > 0 else self.DEFAULT_MAX_TORQUE
            
            for config in self.motor_configs:
                motor_obj = config['obj']
                vel_cmd_multiplier = config['vel_cmd_multiplier']

                with self.lock: # Lock for accessing motor_obj.velocity set by ROS callbacks
                    # Convert target wheel velocity (rad/s) to motor velocity (RPS)
                    motor_target_rps = motor_obj.velocity * RobotSpec.WHEEL_RAD_TO_MOT_RPS * vel_cmd_multiplier
                
                if motor_obj.c: # If controller is active
                    try:
                        await motor_obj.c.set_position(
                            position=math.nan, # Position control mode, but target is velocity
                            velocity=motor_target_rps,
                            feedforward_torque=self.MOTOR_FF_TORQUE, # Applied as is, sign might need to depend on velocity
                            kp_scale=self.MOTOR_KP_SCALE,
                            kd_scale=self.MOTOR_KD_SCALE,
                            maximum_torque=current_max_torque,
                            stop_position=None, # No specific stop position for pure velocity control
                            watchdog_timeout=self.MOTOR_WATCHDOG_TIMEOUT,
                            query=False) # Query separately for all motors after sending all commands potentially
                        
                        state_data = await motor_obj.c.query()
                        if state_data:
                            with self.lock: # Lock for updating shared motor_obj.state
                                motor_obj.state.set_values(state_data)
                        else:
                            rospy.logwarn(f"No state data received for motor {motor_obj.id} ({config['name']})")

                    except Exception as e:
                        rospy.logerr(f"Error commanding/querying motor {motor_obj.id} ({config['name']}): {e}")
            
            await asyncio.sleep(0.01)

    def publish_velocity(self):
        ## Publish controllers velocities
        msg = Float32()
        msg.data = self.c_front_left.state.velocity_ang * -1
        self.pub_front_left_velocity.publish(msg)
        msg.data = self.c_front_right.state.velocity_ang
        self.pub_front_right_velocity.publish(msg)
        msg.data = self.c_rear_left.state.velocity_ang * -1
        self.pub_rear_left_velocity.publish(msg)
        msg.data = self.c_rear_right.state.velocity_ang
        self.pub_rear_right_velocity.publish(msg)

    def publish_position(self):
        ## Publish controllers positions
        msg = Float32()
        msg.data = self.c_front_left.state.position_ang * -1
        self.pub_front_left_angle.publish(msg)
        msg.data = self.c_front_right.state.position_ang
        self.pub_front_right_angle.publish(msg)
        msg.data = self.c_rear_left.state.position_ang * -1
        self.pub_rear_left_angle.publish(msg)
        msg.data = self.c_rear_right.state.position_ang
        self.pub_rear_right_angle.publish(msg)

    def publish_state(self):
        ## Publish controllers state
        is_valid = time.time() - self.c_front_left.state.stamp
        if (is_valid < 1):
            msg = self.c_front_left.state.get_status_msg(-1)
            msg.header.stamp = rospy.Time.now()
            msg.name = "FRONT_LEFT"
            self.pub_front_left_state.publish(msg)
        is_valid = time.time() - self.c_front_right.state.stamp
        if (is_valid < 1):
            msg = self.c_front_right.state.get_status_msg(1)
            msg.header.stamp = rospy.Time.now()
            msg.name = "FRONT_RIGHT"
            self.pub_front_right_state.publish(msg)
        is_valid = time.time() - self.c_rear_left.state.stamp
        if (is_valid < 1):
            msg = self.c_rear_left.state.get_status_msg(-1)
            msg.header.stamp = rospy.Time.now()
            msg.name = "REAR_LEFT"
            self.pub_rear_left_state.publish(msg)
        is_valid = time.time() - self.c_rear_right.state.stamp
        if (is_valid < 1):
            msg = self.c_rear_right.state.get_status_msg(1)
            msg.header.stamp = rospy.Time.now()
            msg.name = "REAR_RIGHT"
            self.pub_rear_right_state.publish(msg)



    def callback_motor_power(self, msg):
        if msg.data:
            with self.lock:
                self.start_power = True
        else:
            with self.lock:
                self.stop_controller = True

    def callback_set_torque(self, msg):
        with self.lock:
            RobotSpec.torque_recent = msg.data / RobotSpec.REDUCER
        with self.lock:
            RobotSpec.TORQUE = msg.data / RobotSpec.REDUCER

    def callback_front_left_vel(self, msg):
        with self.lock:
            self.c_front_left.velocity = msg.data

    def callback_front_right_vel(self, msg):
        with self.lock:
            self.c_front_right.velocity = msg.data

    def callback_rear_left_vel(self, msg):
        with self.lock:
            self.c_rear_left.velocity = msg.data

    def callback_rear_right_vel(self, msg):
        with self.lock:
            self.c_rear_right.velocity = msg.data

    def callback_power_status(self, msg):
        with self.lock:
            self.motors_switch = msg.motor_out_switch

    # Stop controller if motor output switch off message for power module is received.
    def callback_pm_set_motor_switch(self, msg):
        if not msg.data:
            with self.lock:
                self.stop_controller = True

async def main():
    controller = BaseController()

    # Start ROS in a thread separate from the asyncio one.
    def start_ros():
        # Publisher to motor switch on the power module and subscriber for motor switch check.
        controller.motors_switch_pub = rospy.Publisher("/pm/set_motor_switch", Bool, queue_size=10)
        controller.motors_power_switch = rospy.Subscriber('/pm/power_status', Power_status, controller.callback_power_status)

        rospy.init_node('base_controller', disable_signals=True)
        rospy.Subscriber('/base/front_left_wheel_vel', Float32, controller.callback_front_left_vel)
        rospy.Subscriber('/base/front_right_wheel_vel', Float32, controller.callback_front_right_vel)
        rospy.Subscriber('/base/rear_left_wheel_vel', Float32, controller.callback_rear_left_vel)
        rospy.Subscriber('/base/rear_right_wheel_vel', Float32, controller.callback_rear_right_vel)

        rospy.Subscriber('/base/motor_power', Bool, controller.callback_motor_power)
        pub_motor_power_state = rospy.Publisher("/base/motor_power_state", Bool, queue_size=10)

        rospy.Subscriber('/base/set_torque', Float32, controller.callback_set_torque)
        pub_get_torque_set = rospy.Publisher("/base/get_torque_set", Float32, queue_size=10)

        rospy.Subscriber('/pm/set_motor_switch', Bool, controller.callback_pm_set_motor_switch)
        rate = 50
        r = rospy.Rate(rate)  # Hz

        first_run = True
        controller.stop_power = True
        slow_counter = 0
        slow_limit = rate/2 ## 2x per second ToDo: refactor to timer
        rospy.loginfo("Moteus controller initialized.")
        while not rospy.is_shutdown():

            ## Turn off the motor switch in power module
            if controller.stop_power:
                new_msg = Bool()
                new_msg.data = False
                controller.motors_switch_pub.publish(new_msg)
                rospy.loginfo("Wait for Power module disable motor power output...")
                while controller.motors_switch:
                    time.sleep(0.3)
                rospy.loginfo("Motor power output disabled.")

                controller.stop_power = False
                if first_run:
                    rospy.sleep(1)
                    controller.start_power = True
                    first_run = False

            ## Turn on the motor switch in power module
            if controller.start_power:
                new_msg = Bool()
                new_msg.data = True
                controller.motors_switch_pub.publish(new_msg)
                rospy.loginfo("Wait for Power module enable motor power output...")
                while not controller.motors_switch:
                    rospy.sleep(0.3)
                rospy.loginfo("Motor power output enabled.")

                controller.start_power = False
                # let the conrollers in asyncio start too
                controller.start_controller = True
                controller.ros_ready = True
                controller.stop_controller = False

            ## Publish controllers positions
            controller.publish_position()
            ## Publish controllers velocities
            controller.publish_velocity()
            ## Publish controllers states
            if (slow_limit == slow_counter):
                controller.publish_state()
                slow_counter = 0
            slow_counter +=1

            #### over all status ####################
            new_msg = Bool()
            overall_status_ok = True # Assume OK initially

            if not controller.controller_status: # If controller itself is not active
                overall_status_ok = False
            elif RobotSpec.torque_recent == 0.0: # If torque is set to zero (motors might be intentionally disabled)
                overall_status_ok = False
            else:
                # Check each motor's state using motor_configs
                for config in controller.motor_configs:
                    motor_state = config['obj'].state
                    with controller.lock: # Ensure thread-safe access to motor_state
                        if motor_state.fault != ControllerState.FAULT_OK or \
                           motor_state.mode != ControllerState.MODE_POSITION: # Assuming MODE_POSITION is the desired operational mode
                            overall_status_ok = False
                            break # A single motor fault or wrong mode makes overall status not OK
            
            new_msg.data = overall_status_ok
            pub_motor_power_state.publish(new_msg)

            new_msg = Float32()
            new_msg.data = RobotSpec.torque_recent * RobotSpec.REDUCER
            pub_get_torque_set.publish(new_msg)

            r.sleep()

    ros_thread = threading.Thread(target=start_ros)
    ros_thread.start()

    def signal_handler(event, handl):
        new_msg = Bool()
        new_msg.data = False
        controller.motors_switch_pub.publish(new_msg)
        rospy.loginfo("Node base_controller shutting down...")
        rospy.signal_shutdown("end")
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)

    # Run Moteus in asyncio
    try:
        await controller.run()
    except Exception as e:
        print(e)
        traceback.print_exc()
        rospy.logerr("Moteus controller failed!")
        signal_handler("", "")


if __name__ == "__main__":
    asyncio.run(main())
